# Generated by Django 2.2.19 on 2021-08-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workshops.Address')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='participants',
            field=models.ManyToManyField(blank=True, to='workshops.Participant'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='location',
            field=models.ForeignKey(blank=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='workshops.Location'),
        ),
    ]
